/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for tpm
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder tpm_decoder;

extern int tpm_note_key(void *, size_t, unsigned char, const void *, size_t);

