/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for tpm
 */
#include <linux/asn1_ber_bytecode.h>
#include "tpm.asn1.h"

enum tpm_actions {
	ACT_tpm_note_key = 0,
	NR__tpm_actions = 1
};

static const asn1_action_t tpm_action_table[NR__tpm_actions] = {
	[   0] = tpm_note_key,
};

static const unsigned char tpm_machine[] = {
	// PrivateKeyInfo
	[   0] = ASN1_OP_MATCH_ACT,
	[   1] = _tag(UNIV, PRIM, OTS),
	[   2] = _action(ACT_tpm_note_key),
	[   3] = ASN1_OP_COMPLETE,
};

const struct asn1_decoder tpm_decoder = {
	.machine = tpm_machine,
	.machlen = sizeof(tpm_machine),
	.actions = tpm_action_table,
};
