/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for ecrdsa_params
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder ecrdsa_params_decoder;

extern int ecrdsa_param_curve(void *, size_t, unsigned char, const void *, size_t);
extern int ecrdsa_param_digest(void *, size_t, unsigned char, const void *, size_t);

