/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for ecrdsa_pub_key
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder ecrdsa_pub_key_decoder;

extern int ecrdsa_parse_pub_key(void *, size_t, unsigned char, const void *, size_t);

