/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for ecrdsa_params
 */
#include <linux/asn1_ber_bytecode.h>
#include "ecrdsa_params.asn1.h"

enum ecrdsa_params_actions {
	ACT_ecrdsa_param_curve = 0,
	ACT_ecrdsa_param_digest = 1,
	NR__ecrdsa_params_actions = 2
};

static const asn1_action_t ecrdsa_params_action_table[NR__ecrdsa_params_actions] = {
	[   0] = ecrdsa_param_curve,
	[   1] = ecrdsa_param_digest,
};

static const unsigned char ecrdsa_params_machine[] = {
	// EcrdsaParams
	[   0] = ASN1_OP_MATCH,
	[   1] = _tag(UNIV, CONS, SEQ),
	[   2] =  ASN1_OP_MATCH_ACT,		// curve
	[   3] =  _tag(UNIV, PRIM, OID),
	[   4] =  _action(ACT_ecrdsa_param_curve),
	[   5] =  ASN1_OP_MATCH_ACT_OR_SKIP,		// digest
	[   6] =  _tag(UNIV, PRIM, OID),
	[   7] =  _action(ACT_ecrdsa_param_digest),
	[   8] = ASN1_OP_END_SEQ,
	[   9] = ASN1_OP_COMPLETE,
};

const struct asn1_decoder ecrdsa_params_decoder = {
	.machine = ecrdsa_params_machine,
	.machlen = sizeof(ecrdsa_params_machine),
	.actions = ecrdsa_params_action_table,
};
