/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for ecrdsa_pub_key
 */
#include <linux/asn1_ber_bytecode.h>
#include "ecrdsa_pub_key.asn1.h"

enum ecrdsa_pub_key_actions {
	ACT_ecrdsa_parse_pub_key = 0,
	NR__ecrdsa_pub_key_actions = 1
};

static const asn1_action_t ecrdsa_pub_key_action_table[NR__ecrdsa_pub_key_actions] = {
	[   0] = ecrdsa_parse_pub_key,
};

static const unsigned char ecrdsa_pub_key_machine[] = {
	// EcrdsaPubKey
	[   0] = ASN1_OP_MATCH_ACT,
	[   1] = _tag(UNIV, PRIM, OTS),
	[   2] = _action(ACT_ecrdsa_parse_pub_key),
	[   3] = ASN1_OP_COMPLETE,
};

const struct asn1_decoder ecrdsa_pub_key_decoder = {
	.machine = ecrdsa_pub_key_machine,
	.machlen = sizeof(ecrdsa_pub_key_machine),
	.actions = ecrdsa_pub_key_action_table,
};
